### ISSUE TITLE
Translate completely into Russian

### ISSUE THREAD

**Issue by d4fe** [vigri/scantailor-advanced#9]
See screenshots:
![2022-03-05_13-22-37](https://user-images.githubusercontent.com/63813115/156877415-0902d971-13bb-4447-82f6-99acf888dea1.png)
![2022-03-05_13-21-24](https://user-images.githubusercontent.com/63813115/156877419-ea694e18-f328-4582-9f77-c5132570c12d.png)

**Comment by vigri** [comment]
Hi @d4fe 
this is because not all (new) stuff has been translated into Russian.

Unfortunately, I can't help you with that problem, because I don't speak Russian.

Please feel free to submit a pull request.

This is the file you need take a look at: https://github.com/vigri/scantailor-advanced/blob/master/src/translations/scantailor_ru.ts

If you have Qt installed, I would advice you to use **[Qt Linguist](https://doc.qt.io/qt-5/linguist-translators.html#:~:text=Qt%20Linguist%20is%20a%20tool,application%20on%20the%20development%20host.)**

If you don't have Qt Linguist installed simply translate the missing strings directly in the .ts-file. Since the current .ts-file is synced with the code you won't miss any "new" strings.

Feel free to ask if you have any questions.

**Comment by d4fe** [comment]
Thanks! I will try to do this.
